# Generated by Django 5.1.4 on 2024-12-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='main_ingredient',
            field=models.CharField(max_length=10000),
        ),
    ]
