# Generated by Django 5.1.4 on 2024-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_main_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='main_ingredient',
            field=models.CharField(max_length=100000),
        ),
    ]
