# Generated by Django 5.1.4 on 2024-12-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_main_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ease',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
